services:
  zeopp-api:
    container_name: zeopp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9876:8000"
    environment:
      - ZEO_EXEC_PATH=/usr/local/bin/network
      - ENABLE_CACHE=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./workspace:/app/workspace  
      - ./app:/app/app              
      - ./.env:/app/.env            
    restart: unless-stopped
