# Channel Dimensionality API Endpoint
# -*- coding: utf-8 -*-
# Author: Shibo Li
# Date: 2025-05-13

from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from fastapi.responses import JSONResponse
from pathlib import Path

from app.core.runner import ZeoRunner
from app.models.channel_analysis import ChannelAnalysisResponse
from app.utils.file import save_uploaded_file
from app.utils.parser import parse_chan_from_text

router = APIRouter()
runner = ZeoRunner()

@router.post("/api/channel_analysis", response_model=ChannelAnalysisResponse)
async def compute_channel_analysis(
    structure_file: UploadFile = File(...),
    probe_radius: float = Form(...),
    output_filename: str = Form("result.chan"),
    ha: bool = Form(True)
):
    """
    Analyze channel dimensionality using Zeo++ -chan
    """
    input_path: Path = save_uploaded_file(structure_file, prefix="chan")

    args = []
    if ha:
        args.append("-ha")
    args += ["-chan", str(probe_radius), output_filename, input_path.name]

    result = runner.run_command(
        structure_file=input_path,
        zeo_args=args,
        output_files=[output_filename],
        extra_identifier="channel_analysis"
    )

    if not result["success"]:
        return JSONResponse(
            status_code=500,
            content={
                "success": False,
                "message": "Zeo++ failed",
                "stderr": result["stderr"]
            }
        )

    output_text = result["output_data"].get(output_filename)
    if not output_text:
        raise HTTPException(
            status_code=500,
            detail=f"Output file '{output_filename}' was not generated by Zeo++"
        )

    parsed = parse_chan_from_text(output_text)

    return ChannelAnalysisResponse(
        **parsed,
        raw_text=output_text,
        cached=result["cached"]
    )
