# The module is to provide a common functions for all apis of calculation.
# Author: Shibo Li
# Date: 2025-06-16
# Updated: 2025-12-22 - Enhanced error handling
# Updated: 2025-12-31 - Added automatic temp file cleanup, file validation
# Version: 0.3.1


from fastapi import UploadFile, HTTPException, status
from typing import List, Callable, Dict, Any, Type
from pydantic import BaseModel

from app.core.runner import ZeoRunner
from app.core.config import settings
from app.core.exceptions import ZeoppParsingError, ZeoppOutputNotFoundError, ZeoppExecutionError
from app.core.middleware import validate_structure_file, get_allowed_extensions_str
from app.utils.file import save_uploaded_file
from app.utils.cleanup import cleanup_temp_directory
from app.utils.logger import logger

# Create a singleton instance of ZeoRunner
runner = ZeoRunner()

async def process_zeo_request(
    *,
    structure_file: UploadFile,
    zeo_args: List[str],
    output_files: List[str],
    parser: Callable[[str], Dict[str, Any]],
    response_model: Type[BaseModel],
    task_name: str,
    skip_cache: bool = False
) -> Any:
    """
    A generic async function to handle the boilerplate logic for all Zeo++ API requests.

    Args:
        structure_file (UploadFile): The structure file uploaded by the user.
        zeo_args (List[str]): The list of command-line arguments for Zeo++.
        output_files (List[str]): A list of expected output filenames from Zeo++.
        parser (Callable): The function to parse the main output file.
        response_model (Type[BaseModel]): The Pydantic model for the final response.
        task_name (str): A unique name for the task, used for logging and temp file prefixes.
        skip_cache (bool): If True, skip cache and force recalculation.
    """
    # Validate file extension
    if not validate_structure_file(structure_file.filename):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid file type. Allowed extensions: {get_allowed_extensions_str()}"
        )
    
    # Check file size (if available)
    if structure_file.size and structure_file.size > settings.max_upload_size_bytes:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File too large. Maximum size: {settings.max_upload_size_mb}MB"
        )
    
    logger.info(f"[{task_name}] Received new request. Saving file...")
    input_path = save_uploaded_file(structure_file, prefix=task_name)

    try:
        # Create a copy of the args to avoid modifying the original list
        final_zeo_args = zeo_args.copy()
        final_zeo_args.append(input_path.name)

        logger.info(f"[{task_name}] Running Zeo++ with args: {' '.join(final_zeo_args)}")

        # Use async method to run Zeo++ in thread pool, avoiding event loop blocking
        # This allows health checks and other requests to be processed during long calculations
        result = await runner.run_command_async(
            structure_file=input_path,
            zeo_args=final_zeo_args,
            output_files=output_files,
            extra_identifier=task_name,
            skip_cache=skip_cache
        )

        if not result["success"]:
            error_detail = f"Zeo++ exited with code {result['exit_code']}."
            stderr_content = result.get("stderr", "No stderr output.")
            logger.display_error_panel(f"{task_name} Failed", f"{error_detail}\n\n{stderr_content}")
            raise ZeoppExecutionError(
                message=f"Zeo++ execution failed for {task_name}",
                exit_code=result['exit_code'],
                stderr=stderr_content
            )

        main_output_file = output_files[0]
        output_text = result["output_data"].get(main_output_file)

        if output_text is None:
            error_msg = f"Output file '{main_output_file}' was not generated by Zeo++."
            logger.display_error_panel(f"{task_name} Failed", error_msg)
            raise ZeoppOutputNotFoundError(error_msg, expected_file=main_output_file)

        try:
            parsed_data = parser(output_text)
        except ZeoppParsingError as e:
            # Re-raise our custom parsing errors with additional context
            logger.display_error_panel(f"{task_name} Parsing Failed", f"{e.message}\nDetails: {e.details}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail={
                    "message": f"Failed to parse Zeo++ output for {task_name}",
                    "error": e.message,
                    "output_file": e.output_file
                }
            )
        except Exception as e:
            # Catch any other unexpected errors
            error_msg = f"Unexpected error while parsing '{main_output_file}': {str(e)}"
            logger.display_error_panel(f"{task_name} Parsing Failed", error_msg)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail={"message": error_msg, "type": type(e).__name__}
            )

        final_data = {**parsed_data, "cached": result["cached"]}
        logger.success(f"[{task_name}] Task completed successfully.")
        logger.display_data_as_table(final_data, f"Result for {task_name}")
        return response_model(**final_data)
    finally:
        cleanup_temp_directory(input_path.parent)
